inherit_from:
  - .rubocop-relax.yml

AllCops:
  Exclude:
    - tmp/**/*
  DisplayCopNames: true

# Lint

# They are idiomatic
Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: true

# Style

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/TrivialAccessors:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# We adopted raise instead of fail.
Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/SafeNavigation:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/MutableConstant:
  Enabled: false

# 1.8.7 support

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EachWithObject:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: "snake_case"
  AllowedIdentifiers:
    - sha256
    - capture3

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# This should be enabled, but test broke if so, see:
# spec/support/simple_server.rb:149:20
# spec/support/slow_simple_server.rb:15:20
Naming/MethodParameterName:
  Enabled: false

#alerts on some large if blocks
Style/GuardClause:
  Enabled: false

# Metrics

# We've chosen to use Rubocop only for style, and not for complexity or quality checks.
Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

#Security

Security/MarshalLoad:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

#Ignore certain test cases
Bundler/DuplicatedGem:
  Exclude:
    - spec/data/bundles/**/Gemfile

Style/GlobalVars:
  Exclude:
    - spec/support/test_gemstash_server.ru

#changing this causes the jruby build to wedge
Style/ConditionalAssignment:
  Exclude:
    - spec/concurrency_spec.rb
